'use strict';
const fs = require('node:fs'), path = require('node:path');
const root = __dirname;
const family = JSON.parse(fs.readFileSync(path.join(root, 'family-prompts.json'), 'utf8'));
const story = JSON.parse(fs.readFileSync(path.join(root, 'story-voices.json'), 'utf8'));
const escape = s => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const clips = [...story.map(c => ({ ...c, file: 'samples/story/' + c.id + '.mp3' })),
  ...family.map(c => ({ ...c, file: c.recordingFile || 'samples/family/' + (c.auditionId || c.id) + '.mp3' }))];
const present = clips.filter(c => fs.existsSync(path.join(root, c.file))).length;
fs.writeFileSync(path.join(root, 'voice-additions.json'), JSON.stringify({ status: 'approved-integrated', totalClips: 20, clips }, null, 2) + '\n');
function card(c) {
  const audio = fs.existsSync(path.join(root, c.file)) ? `<audio controls preload="metadata" src="${c.file}" aria-label="${escape(c.label)} recording"></audio><a class="download" href="${c.file}" download>Download audio</a>` : '<p>Recording pending</p>';
  return `<article data-id="${c.auditionId || c.id}" data-label="${escape(c.label)}"><h3>${escape(c.label)}</h3>${c.trigger ? `<p class="trigger">${escape(c.trigger)}</p>` : ''}<p class="line">“${escape(c.text)}”</p>${audio}<details class="review"><summary>Review this voice</summary><label>Decision <select aria-label="${escape(c.label)} decision"><option value="">Not reviewed</option><option value="keep">Keep</option><option value="change">Change</option></select></label><label>Notes <textarea rows="2" aria-label="${escape(c.label)} notes" placeholder="Anything you would like changed"></textarea></label></details><details><summary>Voice direction</summary><p>${escape(c.direction)}</p><small>${c.source === 'original-game' ? 'Original baby recording · kept unchanged' : 'GPT-4o Mini TTS · ' + escape(c.voice)}</small></details></article>`;
}
const html = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Bubble Paws — voice review</title><style>
*{box-sizing:border-box}body{margin:0;background:#fcf6ed;color:#665271;font-family:system-ui,sans-serif;line-height:1.5}main{max-width:1040px;margin:auto;padding:38px 22px 60px}h1{color:#765d86;font-size:clamp(26px,4vw,38px);margin:0 0 8px}header p{max-width:760px}h2{margin:32px 0 15px;color:#9271a3;font-size:22px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}article{background:#fffdf9;border:1px solid #e6d8ea;border-radius:22px;padding:22px;box-shadow:0 5px 20px #86668e0c}article.playing{outline:3px solid #a879bf;outline-offset:2px}h3{font-size:17px;margin:0 0 12px;color:#805891}.line{min-height:66px;font-size:17px;color:#6c536f}.trigger{font-size:13px;color:#78617f;margin:0 0 12px}audio{width:100%;margin:10px 0}details{margin-top:12px;font-size:14px;color:#78617f}summary{cursor:pointer}small{color:#78617f}a{color:#76518e}.download{font-size:13px}.pill{display:inline-block;padding:5px 12px;border-radius:20px;background:#ecdfef;font-size:13px}footer{margin-top:36px;font-size:14px;color:#78617f}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0 8px}button{font:inherit;font-weight:600;padding:10px 17px;border:1px solid #d7c1e0;border-radius:14px;color:#76518e;background:#fffdf9;cursor:pointer}button.primary{background:#805891;color:white;border-color:#805891}button:focus-visible,summary:focus-visible,a:focus-visible{outline:3px solid #b882c9;outline-offset:3px}label{display:block;margin-top:10px}select,textarea{display:block;width:100%;margin-top:5px;border:1px solid #d9c9df;border-radius:8px;background:#fffdf9;padding:9px;color:#665271;font:inherit}.status{min-height:24px;font-size:14px;color:#76518e}nav{display:flex;gap:16px;flex-wrap:wrap;margin:22px 0}@media(max-width:620px){.grid{grid-template-columns:1fr}.line{min-height:0}main{padding:25px 16px}}
</style><main><header><span class="pill">20 AI-generated recordings · ready for review</span><h1>A little voice, a lot of heart</h1><p>Eight story moments and twelve family cats. Snowflake and Patches keep their original baby recordings. Their names and families stay clear in the text labels.</p><p>This approved voice pack is now in the game, with the original baby recordings kept. Use “Review this voice” for optional Keep/Change marks and notes; they are saved in this browser.</p><div class="toolbar"><button id="play-all" class="primary">Play all</button><button id="stop">Stop</button><button id="export">Export notes</button></div><p id="status" class="status" role="status" aria-live="polite">${present} of 20 recordings ready.</p><nav><a href="#story">Story moments</a><a href="#marshmallow">Marshmallow’s family</a><a href="#phoebe">Phoebe’s family</a><a href="voice-additions.md">Read the script</a></nav></header><h2 id="story">Story moments</h2><section class="grid">${clips.slice(0,8).map(card).join('')}</section><h2 id="marshmallow">Marshmallow’s family</h2><section class="grid">${clips.slice(8,14).map(card).join('')}</section><h2 id="phoebe">Phoebe’s family</h2><section class="grid">${clips.slice(14).map(card).join('')}</section><footer>Approved game recordings. Original baby voices are preserved. Age, gender and accent are performance directions for listening review. <a href="https://developers.openai.com/api/docs/guides/text-to-speech">Official OpenAI documentation</a></footer></main><script>
const audios=[...document.querySelectorAll('audio')],cards=[...document.querySelectorAll('article')],status=document.getElementById('status');
const storageKey='bubble-paws-voice-review-v1';let reviews={};try{reviews=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{}let sequence=false,next=-1;
function save(){try{localStorage.setItem(storageKey,JSON.stringify(reviews))}catch{status.textContent='Notes cannot be saved in this browser; use Export notes.'}}
cards.forEach(card=>{const id=card.dataset.id,select=card.querySelector('select'),notes=card.querySelector('textarea');select.value=reviews[id]?.decision||'';notes.value=reviews[id]?.notes||'';function update(){reviews[id]={label:card.dataset.label,decision:select.value,notes:notes.value};save()}select.addEventListener('change',update);notes.addEventListener('input',update)});
function stop(){sequence=false;next=-1;audios.forEach(a=>{a.pause();a.currentTime=0});cards.forEach(c=>c.classList.remove('playing'));status.textContent='Playback stopped.'}
async function start(index){const a=audios[index];next=index;try{await a.play()}catch{sequence=false;status.textContent='Playback could not start. Use the recording’s play button.'}}
audios.forEach((a,i)=>{a.addEventListener('play',()=>{if(sequence&&i!==next)sequence=false;audios.forEach(b=>{if(b!==a)b.pause()});cards.forEach(c=>c.classList.remove('playing'));a.closest('article').classList.add('playing');status.textContent='Playing '+(i+1)+' of '+audios.length+': '+a.closest('article').dataset.label});a.addEventListener('pause',()=>a.closest('article').classList.remove('playing'));a.addEventListener('ended',()=>{a.closest('article').classList.remove('playing');if(sequence&&i+1<audios.length)start(i+1);else{sequence=false;status.textContent='Playback finished.'}});a.addEventListener('error',()=>{sequence=false;status.textContent='This recording could not load. Refresh or download the audio.'})});
document.getElementById('play-all').addEventListener('click',()=>{stop();sequence=true;start(0)});document.getElementById('stop').addEventListener('click',stop);
document.getElementById('export').addEventListener('click',()=>{const data={pack:'Bubble Paws — 20-clip review',exportedAt:new Date().toISOString(),reviews:cards.map(c=>({id:c.dataset.id,label:c.dataset.label,decision:reviews[c.dataset.id]?.decision||'',notes:reviews[c.dataset.id]?.notes||''}))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='bubble-paws-voice-review-notes.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
</script></html>`;
for (const name of ['voice-review.html', 'family-auditions.html']) fs.writeFileSync(path.join(root, name), html);
console.log('Voice review: ' + present + '/20 recordings present.');
