// ════════════════════════════════════════════════════════════════
//  ZONES — the twelve biomes of the Whispering Kingdom.
//  Palettes drive the procedural tile art, parallax painter, ambient
//  particles and lighting. `cast` lists the gloomy critters who live in
//  each zone: the `b` / `c` map characters take turns through their list,
//  so every zone has a mix of animals (and a few bugs).
// ════════════════════════════════════════════════════════════════
(function (BB) {
  'use strict';

  BB.ZONES = [
    { // 0 ─ Sunlit Sparkle Gardens
      key: 'gardens', name: 'Sparkle Gardens',
      sky: ['#8fd3ff', '#d9f4ff', '#fff4d6'],
      far: '#9fd8c0', mid: '#6fbf8e', near: '#4f9e6c',
      ground: '#7a5236', groundDark: '#5b3b26', groundLight: '#9a6d48',
      top: '#6cc24a', topLight: '#a4e36b', topDark: '#3f8f35',
      ledge: '#8bd15a', ledgeDark: '#4e9a3a',
      accent: '#ffd1e8', light: '#fff2b3', water: '#6fd0f0',
      ambient: 'pollen', dark: 0,
      cast: { b: ['bunny', 'ladybug', 'hedgehog'], c: ['bluebird', 'hedgehog'] },
    },
    { // 1 ─ Bioluminescent Mushroom Meadow
      key: 'meadow', name: 'Mushroom Meadow',
      sky: ['#2b1b52', '#5a3a8a', '#b07ac0'],
      far: '#4a3378', mid: '#6a4598', near: '#3a2462',
      ground: '#4b2f5e', groundDark: '#321d42', groundLight: '#6b4a82',
      top: '#5ed6b0', topLight: '#a8ffe0', topDark: '#2f9c83',
      ledge: '#e08ad0', ledgeDark: '#9a4c92',
      accent: '#7cf5d4', light: '#aaffee', water: '#7a8cff',
      ambient: 'spores', dark: 0.18,
      cast: { b: ['frog', 'mouse', 'caterpillar'], c: ['mouse', 'beetle'] },
    },
    { // 2 ─ Glimmering Crystal Caverns
      key: 'caves', name: 'Crystal Caverns',
      sky: ['#0b1030', '#1a2458', '#2c3a78'],
      far: '#1c2a60', mid: '#26377a', near: '#141d48',
      ground: '#2f3a70', groundDark: '#1d2550', groundLight: '#46559a',
      top: '#8fdcff', topLight: '#dff6ff', topDark: '#4d8fd0',
      ledge: '#9fb8ff', ledgeDark: '#5a6fc0',
      accent: '#c9a6ff', light: '#b8e8ff', water: '#58c8ff',
      ambient: 'glints', dark: 0.5,
      cast: { b: ['mole', 'bat', 'pillbug'], c: ['bat', 'beetle'] },
    },
    { // 3 ─ Amber Honeycomb Hive
      key: 'hive', name: 'Honeycomb Hive',
      sky: ['#7a3e0c', '#c77716', '#f2b33d'],
      far: '#b8661a', mid: '#d88a22', near: '#8f4a10',
      ground: '#d99a2b', groundDark: '#a8661a', groundLight: '#f2c25a',
      top: '#ffd766', topLight: '#fff0b0', topDark: '#d9a22e',
      ledge: '#f7c948', ledgeDark: '#c38a1e',
      accent: '#fff3c4', light: '#ffe09a', water: '#ffc34a',
      ambient: 'honey', dark: 0.3,
      cast: { b: ['bee', 'bearcub'], c: ['beetle'] },
    },
    { // 4 ─ Serene Rainy Ruins
      key: 'ruins', name: 'Rainy Ruins',
      sky: ['#46566e', '#6f8299', '#a9b9c6'],
      far: '#5c6d84', mid: '#4d5d73', near: '#3a4859',
      ground: '#7d8a96', groundDark: '#58636e', groundLight: '#9aa6b1',
      top: '#6fae7a', topLight: '#a6d6a0', topDark: '#4a8458',
      ledge: '#9c7a5a', ledgeDark: '#6e523a',
      accent: '#bfe7ff', light: '#d8f0ff', water: '#5fb3d6',
      ambient: 'rain', dark: 0.12,
      cast: { b: ['spider', 'owl'], c: ['turtle', 'duckling', 'snailet'] },
    },
    { // 5 ─ Dreamy Cloud Castles
      key: 'clouds', name: 'Cloud Castles',
      sky: ['#9fc6ff', '#ffd6ec', '#fff3dc'],
      far: '#e6dcff', mid: '#f4ecff', near: '#ffffff',
      ground: '#f4f1ff', groundDark: '#cfc6f0', groundLight: '#ffffff',
      top: '#ffffff', topLight: '#ffffff', topDark: '#dcd4ff',
      ledge: '#ffffff', ledgeDark: '#cdbff5',
      accent: '#ffe27a', light: '#fff6d8', water: '#e8f0ff',
      ambient: 'wisps', dark: 0,
      cast: { b: ['bluebird', 'moth'], c: ['lamb'] },
    },
    { // 6 ─ Coral Lagoon
      key: 'lagoon', name: 'Coral Lagoon',
      sky: ['#6fd0ff', '#bff0ff', '#fff1c9'],
      far: '#8fd6d8', mid: '#5fb8b0', near: '#2f8a86',
      ground: '#e8c88c', groundDark: '#c9a066', groundLight: '#f6e2b0',
      top: '#f6e2b0', topLight: '#fff6d8', topDark: '#d8b87a',
      ledge: '#b98a5a', ledgeDark: '#7a5a3a',
      accent: '#ff9fb8', light: '#dff8ff', water: '#2fc0d8',
      ambient: 'bubbles', dark: 0,
      cast: { b: ['crab', 'seal', 'jellyfish'], c: ['fish', 'crab'] },
    },
    { // 7 ─ Sunny Dunes
      key: 'dunes', name: 'Sunny Dunes',
      sky: ['#ffa860', '#ffd49a', '#fff0c8'],
      far: '#f0b27a', mid: '#d98d58', near: '#a85e32',
      ground: '#d98d58', groundDark: '#b06838', groundLight: '#f0b27a',
      top: '#f5cf8e', topLight: '#ffe8b8', topDark: '#d9a560',
      ledge: '#a8764a', ledgeDark: '#6e4a2a',
      accent: '#7cc85a', light: '#fff0c0', water: '#3fc0d8',
      ambient: 'sand', dark: 0,
      cast: { b: ['fennec', 'meerkat', 'lizard'], c: ['scarab', 'meerkat'] },
    },
    { // 8 ─ Frosty Peaks
      key: 'frost', name: 'Frosty Peaks',
      sky: ['#4a66b0', '#a8c8f0', '#e8f4ff'],
      far: '#c8dcf5', mid: '#9ab8e0', near: '#5e7cb4',
      ground: '#8fa8d0', groundDark: '#647cae', groundLight: '#b8cce8',
      top: '#ffffff', topLight: '#ffffff', topDark: '#d8e6f8',
      ledge: '#c8e8ff', ledgeDark: '#6a9ad0',
      accent: '#9ff0e0', light: '#e8f8ff', water: '#7ad0f0',
      ambient: 'snow', dark: 0,
      cast: { b: ['penguin', 'polarcub', 'arcticfox'], c: ['owl', 'penguin'] },
    },
    { // 9 ─ Autumn Woods
      key: 'autumn', name: 'Autumn Woods',
      sky: ['#f29a52', '#f8d4a0', '#fff0d8'],
      far: '#e8a070', mid: '#c8663a', near: '#7a3418',
      ground: '#6a4a34', groundDark: '#4a3022', groundLight: '#8a6448',
      top: '#e8783a', topLight: '#ffb060', topDark: '#b0482a',
      ledge: '#9a6a3a', ledgeDark: '#5a3a1a',
      accent: '#ffd04a', light: '#fff0c8', water: '#6fb8d8',
      ambient: 'leaves', dark: 0.05,
      cast: { b: ['squirrel', 'fawn', 'raccoon'], c: ['hedgehog'] },
    },
    { // 10 ─ Moonlit Hot Springs
      key: 'springs', name: 'Moonlit Springs',
      sky: ['#2e2452', '#7a5288', '#e898a6'],
      far: '#5e5082', mid: '#44405e', near: '#24243e',
      ground: '#6a6a7a', groundDark: '#4a4a5a', groundLight: '#8a8a9a',
      top: '#6fb87a', topLight: '#a8e0a0', topDark: '#3f7a4a',
      ledge: '#c0484a', ledgeDark: '#6a2a2a',
      accent: '#ffb0c0', light: '#ffd8a8', water: '#6fd8d0',
      ambient: 'steam', dark: 0.12,
      cast: { b: ['capybara', 'monkey'], c: ['koi'] },
    },
    { // 11 ─ Starlight Sky
      key: 'starlight', name: 'Starlight Sky',
      sky: ['#070722', '#241654', '#54347e'],
      far: '#2a2a6a', mid: '#3a2a7a', near: '#160e3a',
      ground: '#3a3a8a', groundDark: '#22225a', groundLight: '#5a5ab0',
      top: '#b8a0ff', topLight: '#f0e8ff', topDark: '#7a60d0',
      ledge: '#ffe8a0', ledgeDark: '#c0a040',
      accent: '#ffe27a', light: '#e8e0ff', water: '#8a7aff',
      ambient: 'stars', dark: 0.15,
      cast: { b: ['dragon', 'unicorn', 'bunny'], c: ['lamb', 'bat'] },
    },
  ];
})(window.BB);
